In [2]:
import numpy as np

In [ ]:
#1. Create the following 8×8 matrix:
# [[0 1 0 1 0 1 0 1],[1 0 1 0 1 0 1 0], ... ]
arr = np.zeros((8,8))
# for i in range(0,8):
#     if i % 2 == 0:
#         for j in range(1,8,2):
#             arr[i,j] = 1
#     else:
#         for j in range(0,8,2):
#             arr[i,j] = 1
# arr

arr[1::2,::2] = 1
arr[::2,1::2] = 1
arr

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [5]:
#2. Create a 5×5 matrix where the border contains 1s and the inside contains 0s.
# Expected:
# [[1 1 1 1 1],[1 0 0 0 1],[1 0 0 0 1],[1 0 0 0 1],[1 1 1 1 1]]

arr = np.ones((5,5))
arr[1:-1, 1:-1] = 0
arr


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#3. Given: arr = np.array([5,12,7,18,25,3,15])
# Replace all values greater than 10 with -1.
arr = np.array([5,12,7,18,25,3,15])
arr = np.where(arr>10, -1,arr)
arr


array([ 5, -1,  7, -1, -1,  3, -1])

In [10]:
#4. Create an array from 1 to 100 and extract only numbers divisible by 3.
arr = np.arange(1,101)
arr[arr%3==0]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [12]:
#5. Find common elements between:
# a = [1,2,3,4,5]
# b = [4,5,6,7,8]
a = np.arange(1,6)
b = np.arange(4,9)
np.intersect1d(a,b)

array([4, 5])

In [15]:
#6. Given: arr = [1,2,4,6,7,9]
# Find missing numbers between 1 and 9.
arr = np.array([1,2,4,6,7,9])
a = np.arange(1,10)
np.setdiff1d(a,arr)

array([3, 5, 8])

In [17]:
#7. Find the maximum value from each row:
# [[4,8,2],[9,1,5],[7,6,3]]
arr = np.array([[4,8,2],[9,1,5],[7,6,3]])
arr.max(axis=1)

array([8, 9, 7])

In [20]:
#8. Find the sum of each column:
# [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr.sum(axis=0)

array([12, 15, 18])

In [21]:
#9. Multiply:
# A=[[1,2],[3,4]]
# B=[[5,6],[7,8]]
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A * B

array([[ 5, 12],
       [21, 32]])

In [23]:
#10. Convert a 4×4 matrix into a 1D array.
A = np.identity(4)
A.flatten()


array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [24]:
#11. Convert np.arange(24) into a 2×3×4 array.
arr = np.arange(24)
arr.reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [28]:
#12. Given [[1,2,3],[4,5,6],[7,8,9]], reverse every row.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[::1,::-1]

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [29]:
#13. Given [[1,2,3],[4,5,6],[7,8,9]], reverse every column.
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[::-1,::1]

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [31]:
#14. Sort [10,5,20,15,8,3] in ascending order.
arr = np.array([10,5,20,15,8,3])
arr.sort()
arr

array([ 3,  5,  8, 10, 15, 20])

In [34]:
#15. Sort every row of [[9,4,7],[2,8,1],[6,3,5]].
arr = np.array([[9,4,7],[2,8,1],[6,3,5]])
arr.sort(axis=1)
arr

array([[4, 7, 9],
       [1, 2, 8],
       [3, 5, 6]])

In [35]:
#16. Given [11,22,35,40,55,60], find indices where numbers are even.
arr = np.array([11,22,35,40,55,60])
np.where(arr%2==0)

(array([1, 3, 5]),)

In [39]:
#17. Count unique elements in [1,2,2,3,4,4,5,5,5].
arr = np.array([1,2,2,3,4,4,5,5,5])
np.unique(arr).size

5

In [44]:
#18. Find frequency of every element in [1,2,2,3,3,3,3,4,4,4,4,4].
arr = np.array([1,2,2,3,3,3,3,3,3,2,4,4,4,4,4,4,4,])
np.unique(arr,return_counts=True)

(array([1, 2, 3, 4]), array([1, 3, 6, 7]))

In [76]:
#19. Normalize [10,20,30,40,50] using Min-Max normalization.
arr = np.array([10,20,30,40,50])
a_min = arr.min()
a_max = arr.max()
norm_data = (arr-a_min)/(a_max-a_min)
norm_data

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [46]:
#20. Generate a 5×5 matrix of random integers between 1 and 100.
arr = np.random.randint(1,100,size=(5,5))
arr

array([[97, 73, 16, 79, 82],
       [ 6, 58, 69, 21, 36],
       [70, 37, 72, 22,  3],
       [97, 50, 93, 19, 74],
       [56,  7, 57, 39, 94]], dtype=int32)

In [49]:
#21. Find the second largest element in [10,50,20,80,60,90].
arr = np.array([10,50,20,80,60,90])
arr.sort()
arr[-2]

np.int64(80)

In [57]:
#22. Find all duplicate values in [1,2,3,4,2,5,6,1,7].
arr = np.array([1,2,3,4,2,5,6,1,7])
v,vc = np.unique(arr,return_counts=True)
dup = v[vc>1]
dup


array([1, 2])

In [62]:
#23. Find the sum of diagonal elements in [[1,2,3],[4,5,6],[7,8,9]].
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Trace method : ",np.trace(arr))
print("Diag function : ",np.diag(arr).sum())


Trace method :  15
Diag function :  15


In [4]:
#24. Create a 10×10 multiplication table using NumPy.
nums = np.arange(1, 11)

#Multiply the 1D array by its vertical reshape to trigger broadcasting
multiplication_table = nums * nums[:, np.newaxis]

print(multiplication_table)

# nums = np.arange(1, 11)
# print("original matrix",nums)
# # print("row matrix",nums[np.newaxis, :])
# nums = np.arange(1, 11)
# print("column matrix",nums[:,np.newaxis])

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [1]:
import numpy as np