In [3]:
import numpy as np
arr = np.array([[1,2,3,4]])
print(arr)
arr

[[1 2 3 4]]


array([[1, 2, 3, 4]])

In [1]:
import numpy as np 
import time

n = 1000

list1 = list(range(n))
list2 = list(range(n))

start = time.time()
result_list = [list1[i] + list2[i] for i in range(n)]
list_time = time.time() - start

arr1 = np.array(n)
arr2 = np.array(n)

start = time.time()
result_arr = arr1 + arr2
numpy_time = time.time() - start

print(f"List Time : {list_time:.6f} sec")
print(f"Numpy Time : {numpy_time:.6f} sec")
print(f"Numpy is approximately  {list_time/numpy_time:.6f}X faster")


List Time : 0.000220 sec
Numpy Time : 0.000044 sec
Numpy is approximately  5.010870X faster


In [2]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)


[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
arr = np.array([[
    [1,2],[3,4],
    [5,6]
                ]])
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


[[[1 2]
  [3 4]
  [5 6]]]
(1, 3, 2)
3
6
int64


In [17]:
arr= np.zeros((2,3),np.int8)
print(arr)

[[0 0 0]
 [0 0 0]]


In [20]:
arr = np.ones((2,3),np.int8)
print(arr)

[[1 1 1]
 [1 1 1]]


In [24]:
arr = np.empty((2,3),np.int8)
print(arr)

[[1 1 1]
 [1 1 1]]


In [35]:
arr = np.eye(3,5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [37]:
arr = np.identity(5)
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [40]:
arr = np.arange(0,100,2)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.dtype)
print(arr.size)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
(50,)
1
int64
50


In [ ]:
arr = np.linspace(0.1,1,50)
print(arr)

[0.1        0.11836735 0.13673469 0.15510204 0.17346939 0.19183673
 0.21020408 0.22857143 0.24693878 0.26530612 0.28367347 0.30204082
 0.32040816 0.33877551 0.35714286 0.3755102  0.39387755 0.4122449
 0.43061224 0.44897959 0.46734694 0.48571429 0.50408163 0.52244898
 0.54081633 0.55918367 0.57755102 0.59591837 0.61428571 0.63265306
 0.65102041 0.66938776 0.6877551  0.70612245 0.7244898  0.74285714
 0.76122449 0.77959184 0.79795918 0.81632653 0.83469388 0.85306122
 0.87142857 0.88979592 0.90816327 0.92653061 0.94489796 0.96326531
 0.98163265 1.        ]


In [46]:
arr = np.linspace(0.1,1,50,endpoint=True,retstep=True,dtype=float)
print(arr)

(array([0.1       , 0.11836735, 0.13673469, 0.15510204, 0.17346939,
       0.19183673, 0.21020408, 0.22857143, 0.24693878, 0.26530612,
       0.28367347, 0.30204082, 0.32040816, 0.33877551, 0.35714286,
       0.3755102 , 0.39387755, 0.4122449 , 0.43061224, 0.44897959,
       0.46734694, 0.48571429, 0.50408163, 0.52244898, 0.54081633,
       0.55918367, 0.57755102, 0.59591837, 0.61428571, 0.63265306,
       0.65102041, 0.66938776, 0.6877551 , 0.70612245, 0.7244898 ,
       0.74285714, 0.76122449, 0.77959184, 0.79795918, 0.81632653,
       0.83469388, 0.85306122, 0.87142857, 0.88979592, 0.90816327,
       0.92653061, 0.94489796, 0.96326531, 0.98163265, 1.        ]), np.float64(0.018367346938775512))


In [1]:
import numpy as np
arr = np.full((2,3),7)
print(arr)

[[7 7 7]
 [7 7 7]]


In [2]:
arr = np.full((2,3),[1,2,3])
print(arr)

[[1 2 3]
 [1 2 3]]


In [5]:
a=[1.5,2,3,5.5,7]
arr = np.random.choice(a,(10,10),replace=True,p=[0.3,0.2,0.05,0.05,0.4])
print(arr)

[[2.  3.  7.  2.  1.5 7.  1.5 1.5 1.5 7. ]
 [3.  7.  7.  1.5 2.  7.  1.5 2.  1.5 7. ]
 [2.  2.  1.5 5.5 1.5 1.5 7.  3.  7.  7. ]
 [3.  1.5 1.5 1.5 7.  7.  7.  7.  1.5 1.5]
 [1.5 1.5 3.  7.  1.5 7.  2.  7.  7.  1.5]
 [7.  7.  7.  7.  7.  2.  7.  1.5 7.  1.5]
 [1.5 7.  1.5 2.  7.  7.  2.  7.  5.5 1.5]
 [7.  1.5 1.5 1.5 1.5 7.  1.5 2.  7.  2. ]
 [7.  7.  1.5 2.  7.  2.  3.  1.5 2.  2. ]
 [2.  7.  2.  1.5 2.  2.  7.  7.  7.  2. ]]


In [8]:
a=['True','False']
arr = np.random.choice(a,(10,10),replace=True,p=[0.8,0.2])
print(arr)

[['True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True' 'False' 'True' 'True' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True' 'True' 'False' 'True' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True' 'True' 'True' 'False' 'True' 'True' 'True']
 ['True' 'True' 'True' 'True' 'True' 'False' 'False' 'True' 'False'
  'True']
 ['True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'True' 'False']
 ['False' 'False' 'True' 'True' 'True' 'True' 'True' 'True' 'False'
  'True']
 ['True' 'False' 'True' 'True' 'True' 'False' 'True' 'True' 'False'
  'True']
 ['True' 'False' 'False' 'True' 'True' 'False' 'True' 'True' 'False'
  'True']]


In [3]:
arr = np.random.rand(5,3)
print(arr)

[[0.02224068 0.85394087 0.74949788]
 [0.49847881 0.3379406  0.1494957 ]
 [0.32130147 0.74987242 0.02602955]
 [0.8574193  0.47656729 0.36717808]
 [0.19145372 0.44169443 0.45439264]]


In [10]:
arr = np.random.randint(0,10,(10,10))
print(arr)

[[4 6 9 6 4 8 2 0 2 7]
 [5 3 7 5 6 0 0 7 1 6]
 [0 3 1 7 9 0 4 6 7 1]
 [4 4 5 1 9 2 5 3 3 4]
 [1 7 1 1 4 4 3 8 8 8]
 [0 5 9 2 8 2 8 6 1 6]
 [9 1 2 7 2 6 6 4 5 7]
 [8 6 6 8 2 3 2 8 3 2]
 [4 9 2 8 4 2 4 9 5 4]
 [2 8 8 8 3 8 1 0 1 5]]


In [11]:
a = [1,2,3,4,[5,6,7],8,9]
a[4][1]

6

In [17]:
ar = np.array([1,2,3,4,5])
print(ar[2])


3


In [21]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr[0:2,0])
print(arr[0:2,0:2])
print(arr[1:2,1:3])


[1 4]
[[1 2]
 [4 5]]
[[5 6]]


In [ ]:
#fancy inda
arr = np.array([1,2,3,4,5,6,7,8,9])
a=[1,2,4]
print(arr[a])


[2 3 5]


In [25]:
arr=np.array([25,26,19,45,20,12,24,13,17,41,36,39])
print(arr[arr<20])
print(arr<20)

[19 12 13 17]
[False False  True False False  True False  True  True False False False]


In [36]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
c=a-b
c=a*b
c=a/b
c=a%b
c=a**b
print(c)

[  1  32 729]


In [6]:
import numpy as np
a = np.zeros((5,5))
a[1:4,1:4] = 1
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [3]:
import numpy as np 
arr =[[[[1,2,3,4]]]]
for i in np.nditer(arr):
    print(i)

1
2
3
4


In [5]:
arr =[[[[1,2,3,4]]]]
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3
(0, 0, 0, 3) 4


In [6]:
arr =[[[[1,2,3],
        [4,5,6],
        [7,8,9]]]]
for i,j in np.ndenumerate(arr):
    print(i,j)

(0, 0, 0, 0) 1
(0, 0, 0, 1) 2
(0, 0, 0, 2) 3
(0, 0, 1, 0) 4
(0, 0, 1, 1) 5
(0, 0, 1, 2) 6
(0, 0, 2, 0) 7
(0, 0, 2, 1) 8
(0, 0, 2, 2) 9


In [10]:
arr = np.array([1,2,3,4,5,6,7,8])
arr1 = np.split(arr,4)
print(arr1)


[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [16]:
arr = np.array([[1,2,3,4],
               [5,6,7,8]])
arr1 = np.split(arr,4,axis=1)
print(arr1)

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]


In [17]:
arr = np.transpose([[1,2,3,4],
                [5,6,7,8]])
print(arr)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [19]:
arr = np.sort([3,4,2,5,1])
print(arr)

[1 2 3 4 5]


In [21]:
arr = np.sort([[3,4,2,5,1],
               [6,7,5,9,2,]])
print(arr)

[[1 2 3 4 5]
 [2 5 6 7 9]]


In [24]:
arr = np.array([3,2,1,5,6,7,4])
#print(np.sort(arr,axis=-1,kind="merge"))
print(arr[::-1])

[4 7 6 5 1 2 3]


In [26]:
arr = np.array([3,2,1,5,6,7,4])
print(np.where(arr%2==0,0,arr))
print(np.where(arr%2==0))

[3 0 1 5 0 7 0]
(array([1, 4, 6]),)


In [27]:
arr = np.array([[3,2,1,5],[6,7,4,5]])
print(np.where(arr%2==0,0,arr))
print(np.where(arr%2==0))

[[3 0 1 5]
 [0 7 0 5]]
(array([0, 1, 1]), array([1, 0, 2]))


In [32]:
arr = np.array([3,2,1,5,6,7,4])
print(np.delete(arr,(2,4)))


[3 2 5 7 4]


In [41]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.delete(arr,0))
print(np.delete(arr,1,axis=0))
print(np.delete(arr,1,axis=1))

[2 3 4 5 6 7 8 9]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [42]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.delete(arr,np.where(arr>5)))

[4 5 6 7 8 9]


In [43]:
arr = np.array([3,2,1,5,6,7,4])
print(np.insert(arr,[2,5],[20,25]))

[ 3  2 20  1  5  6 25  7  4]


In [2]:
import numpy as np
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(np.insert(arr,2,[1,2,5],axis=0))
print(np.insert(arr,2,99,axis=0))
print(np.insert(arr,3,[1,2,5],axis=1))

[[1 2 3]
 [4 5 6]
 [1 2 5]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [99 99 99]
 [ 7  8  9]]
[[1 2 3 1]
 [4 5 6 2]
 [7 8 9 5]]


In [3]:
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([2,1,6,7,8])
print(np.intersect1d(arr1,arr2))
print(np.intersect1d(arr1,arr2,assume_unique=True,return_indices=True))

[1 2]
(array([1, 2]), array([0, 1]), array([1, 0]))


In [60]:
from functools import reduce
arr1 =np.array([1,2,3,4,5])
arr2 =np.array([2,1,6,7,8])
arr3 =np.array([3,8,9,7,3])
print(reduce(np.union1d,(arr1,arr2,arr3)))

[1 2 3 4 5 6 7 8 9]


In [5]:
import numpy as np 
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(np.reshape(arr,(3,4)))
print(arr.reshape(3,4))
print(arr.reshape(4,-1))
print(arr.reshape(-1,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
arr1 = np.array([[1,2,3,4,5,6]])
arr2 = np.array([[7,8,9,10,11,12]])
#print(np.concatenate((arr1,arr2)))
print(np.concatenate((arr1,arr2),axis=0))


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [20]:
arr = np.array([1,2,0,3,4,0,5,6,0,7,8,0,8,9,0])
print(np.count_nonzero(arr))

10


In [23]:
arr = np.array([1,2,0,3,4,0,5,6,0,7,8,0,8,9,0])
print(np.unique(arr))

[0 1 2 3 4 5 6 7 8 9]


In [24]:
arr = np.array([1,2,0,3,4,0,5,6,0,7,8,0,8,9,0])
print(np.unique(arr).size)

10


In [28]:
arr = np.array([0,1,2,0,3,4,0,5,6,0,7,8,0,8,9,0,0,0])
print(np.trim_zeros(arr))
print(np.trim_zeros(arr,trim='b'))
print(np.trim_zeros(arr,trim='f'))

[1 2 0 3 4 0 5 6 0 7 8 0 8 9]
[0 1 2 0 3 4 0 5 6 0 7 8 0 8 9]
[1 2 0 3 4 0 5 6 0 7 8 0 8 9 0 0 0]


In [29]:
arr = np.array([1,2,3,4,5])
arr1 = np.copy(arr)
print(arr1)
arr3 = arr.view()
print(arr3)


[1 2 3 4 5]
[1 2 3 4 5]


In [31]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

print(np.setxor1d(arr1,arr2))
print(np.setdiff1d(arr1,arr2))


[1 2 3 7 8 9]
[1 2 3]


In [32]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

print(np.dot(arr1,arr2))

154


In [33]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])
print(np.dot(arr1,arr2))

[[19 22]
 [43 50]]


In [34]:
arr1 = np.array([[1,2],
                 [3,4]])
arr2 = np.array([[5,6],
                 [7,8]])
print(np.cross(arr1,arr2))

[-4 -4]


C:\Users\moham\AppData\Local\Temp\ipykernel_74976\3471758326.py:5: DeprecationWarning: Arrays of 2-dimensional vectors are deprecated. Use arrays of 3-dimensional vectors instead. (deprecated in NumPy 2.0)
  print(np.cross(arr1,arr2))


In [35]:
arr1 = np.array([[1,2,3]])
arr2 = np.array([[4,5,6]])
print(np.cross(arr1,arr2))

[[-3  6 -3]]


In [38]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1@arr2)

32


In [11]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))
print(np.divide(arr1,arr2))
print(np.multiply(arr1,arr2))
print(np.power(arr1,arr2))

print(np.sqrt(arr1))
print(np.exp(arr1))
print(np.log(arr1))
print(np.sin(arr1))
print(np.cos(arr1))
print(np.abs(arr1))

[5 7 9]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[  1  32 729]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 2 3]
