In [1]:
#Create a numpy array
#Create an array containing number from 1 to 10.
import numpy as np 
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
#Check array properyies
#create an array and print: shap, size, datatype, number of dimentions.
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.shape) 
print(arr.size) 
print(arr.dtype)
print(arr.ndim)


(6,)
6
int64
1


In [11]:
#Create a zeros array
#Create a 3*3 array filled with zeros.
arr=np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [12]:
#Create a ones array
#Create a 4*2 array filled with ones.
arr = np.ones((4,2))
print(arr)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
#Create an identity matrix
#create a 5*5 identity matrix.
arr = np.identity((5))
print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#Create a range array
# Create an array containing number 10 to 50 with a step of 5.
arr = np.arange(10,50,5)
print(arr)

[10 15 20 25 30 35 40 45]


In [ ]:
#create evenly spaced values 
#create 11 evenly spaced number between 0 to 100.


In [18]:
#Reshape an array.
# Create an array frome 1 to 12 and reshape it into a 3*4 matrix.
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr.reshape(3,4)) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
#Find the first element.
#create an array and print its first eliment.
arr = np.array([1,2,3,4,5])
print(arr[0])

1


In [21]:
#Find the last element.
#create an array and print its last eliment.
arr = np.array([1,2,3,4,5])
print(arr[-1])

5


In [22]:
#Slice an array
#Create an array from 1 to 20 and print elements from index 5 to index 10.
arr = np.array((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20))
print(arr[5:10])

[ 6  7  8  9 10]


In [23]:
#Reverse an array
#Create an array from 1 to 10 and reverse it.
arr = np.array([1,2,3,4,5])
print(arr[::-1])

[5 4 3 2 1]


In [25]:
#Find maximum value
#Create an array and find its largest value.
arr = np.array([1,2,3,4,5])
print(arr.max())

5


In [ ]:
#Find minimum value
#Create an array and find its smallest value.
arr = np.array([1,2,3,4,5])
print(arr.min())

1


In [27]:
#Calculate sum
#Find the sum of all elements in an array.
arr = np.array([1,2,3,4,5])
print(arr.sum())

15


In [28]:
#Calculate mean
#Find the average of the array: [10, 20, 30, 40, 50].
arr = np.array([10, 20, 30, 40, 50])
print(arr.mean())

30.0


In [29]:
#Calculate median
#Find the median of: [2, 4, 6, 8, 10].
arr = np.array([2, 4, 6, 8, 10])
print(np.median(arr))

6.0


In [30]:
#Find standard deviation
#Calculate the standard deviation of: [5, 10, 15, 20, 25].
arr = np.array([5, 10, 15, 20, 25])
print(arr.std())

7.0710678118654755


In [31]:
#Add two arrays
#Add [1, 2, 3] and [4, 5, 6].
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1+arr2)

[5 7 9]


In [32]:
#Multiply two arrays
#Multiply [2, 4, 6] and [3, 5, 7] element-wise.
arr1 = np.array([2, 4, 6])
arr2 = np.array([3, 5, 7])
print(arr1*arr2)

[ 6 20 42]


In [34]:
#Square all elements
#Create an array from 1 to 10 and find the square of every element.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.square(arr))

[  1   4   9  16  25  36  49  64  81 100]


In [36]:
#Find even numbers
#Create an array from 1 to 20 and print only even numbers.
arr = np.arange(1,20)
print(np.where(arr%2==1))

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]),)


In [37]:
#Count elements greater than 50
#Given [10, 25, 60, 75, 30, 90, 45], count how many elements are greater than 50.
arr = np.array([10, 25, 60, 75, 30, 90, 45])
print(np.sum(arr>50))


3


In [38]:
#Transpose a matrix
#Create [[1,2,3],[4,5,6]] and find its transpose.
arr = np.transpose([[1,2,3],[4,5,6]])
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [41]:
#Find row-wise sum
#Given [[1,2,3],[4,5,6],[7,8,9]], find the sum of each row.
arr = np.array( [[1,2,3],[4,5,6],[7,8,9]])
print(arr.sum(axis=1))

[ 6 15 24]


In [4]:
#Bonus Challenge
#Create a 5×5 matrix containing numbers from 1 to 25.
import numpy as np
arr = np.arange(1,26)
print(arr.reshape(5,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [7]:
#Bonus Challenge
#Replace all odd numbers in an array with -1.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(np.where(arr%2==1,-1,arr))

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [8]:
#Bonus Challenge
#Find all numbers divisible by 3 in an array from 1 to 30.
arr = np.arange(1,30)
print(np.sum(arr%3==0))

9


In [11]:
#Bonus Challenge
#Create a random array of 10 integers between 1 and 100.
arr = np.linspace(1,10,100,endpoint=True,retstep=True,dtype=int)
print(arr)

(array([ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,
        7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,
        8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10]), np.float64(0.09090909090909091))


In [15]:
arr = np.random.randint(0,100,size=10)
print(arr)

[62 92 85  5 92 27 54 13 69 25]


In [18]:
arr = np.array([62,85,5,92,27,54,13,69,25])
print(np.argmax(arr))
print(np.argmin(arr))

3
2


In [ ]:
pip install pandas