In [5]:
import numpy as np
arr =np.array([1,2,3,4])

print(arr)


[1 2 3 4]


In [6]:
import numpy as np
arr = np.array([1, 2, 3])
result = arr * 2
print(arr)

[1 2 3]


In [5]:
import numpy as np 
print(np.random.rand(3))

[0.54444735 0.22657305 0.29025724]


In [7]:
import numpy as np
arr = np.array([1,2,3])
print(arr.itemsize)

8


In [1]:
import numpy as np
arr =np.array([
    [1,2],
    [3,4]
])
print(arr.ndim)


2


In [1]:
import numpy as np
np.full((2,2),-0.09)

array([[-0.09, -0.09],
       [-0.09, -0.09]])

In [14]:
import numpy as np
arr = np.array([1,2,3])
new_arr = arr.astype(float)
print(new_arr)

[1. 2. 3.]


In [12]:
import numpy as np 
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[-2:-1])

[[40 50 60]]


In [22]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[1:2,0:3])

[[40 50 60]]


In [23]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0:1,0:3])

[[10 20 30]]


In [33]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[2,1])

80


In [36]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[2:3,1:2])

[[80]]


In [37]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0:1,1:3])

[[20 30]]


In [41]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[0:3,0:1])

[[10]
 [40]
 [70]]


In [46]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[-3:-2])

[[10 20 30]]


In [49]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[1:3,1:3])

[[50 60]
 [80 90]]


In [67]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[-2:,-2:])

[[50 60]
 [80 90]]


In [69]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print(arr[-3:,-2:])

[[20 30]
 [50 60]
 [80 90]]


In [81]:
arr = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])

nn = arr[-1:-3:-1]
nn[:,-2:]

array([[80, 90],
       [50, 60]])

In [92]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-4:-1,-4:-1])

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-4:-1,-4:-1])

In [93]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-3,-4])

12


In [106]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-3:-5:-1,])

[[11 12 13 14 15]
 [ 6  7  8  9 10]]


In [2]:
import numpy as np
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-3,-2])

14


In [33]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
print(arr[-1:-3:-1,-4:-6:-1])
print(arr[-1:-3:-1,-5:-3])

[[22 21]
 [17 16]]
[[21 22]
 [16 17]]


In [23]:
arr = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
arr[1,4]=100
arr[2,1]=1200
print(arr)

[[   1    2    3    4    5]
 [   6    7    8    9  100]
 [  11 1200   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24   25]]


In [30]:
arr = np.array([1,2,3,4,5])
print(arr[::-1])
print(arr[-2])
arr[1:3]=1000
print(arr)

[5 4 3 2 1]
4
[   1 1000 1000    4    5]


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[::2])

[1 3 5 7 9]


In [45]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.add(a,b)

array([ 7,  9, 11, 13, 15])

In [49]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.power(a,2)

array([ 1,  4,  9, 16, 25])

In [47]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.subtract(a,b)

array([-5, -5, -5, -5, -5])

In [52]:
a = np.array([12,2,3,4,5])
b = np.array([6,7,8,9,10])
np.divide(a,b)

array([2.        , 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [53]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.square(a)

array([ 1,  4,  9, 16, 25])

In [54]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [55]:
a = np.array([-1,2,3,-4,-5])
# b = np.array([6,7,8,9,10])
np.abs(a)

array([1, 2, 3, 4, 5])

In [ ]:
# they can give reminder value
a = np.array([1,2,3,4,5])

np.mod(a,2)

array([1, 0, 1, 0, 1])

In [ ]:
import numpy as np
a = np.array([[
    [1,2],
    [3,4]
],[
    [5,6],
    [7,8]
]
])
#print(a[:1,:,:])
#print(a[1:2,:,:])
#print(a[0:2,1:2,:])
#print(a[0:2,:,:1])
#print(a[0:2,:,1:2])
#print(a[-2,-1,-1])
#print(a[-1,-2,-2])
#print(a[:,:,-2:-1])
#print(a[:,-1:,-2:])
print(a[:,-1:,-1])
print(a[:,-2:-1,-1]) 


[[4]
 [8]]
[[2]
 [6]]


In [65]:
data = np.array([2,4,3,5,6])
print(np.var(data))
print(np.std(data))
print(np.max(data))
print(np.min(data))

2.0
1.4142135623730951
6
2
